### ISSUE TITLE
Bad PDF quality

### ISSUE THREAD

**Issue by N1co93** [elektro-wolle/imap-pdf-ocr#3]
I just noticed that the returned PDF file with OCR-Layer have a bad image quality. 

You can also see this in the file size, for example the original PDF have a size of 343 KB, after the OCR layer is added the PDF file have a size of 70 KB.

Is it possible that you can improve the PDF quality?

Btw. is this project still being maintained? The last commit was back in 2018. 

Thank you in advance

**Comment by elektro-wolle** [comment]
The pdf quality is automatically reduced to 72dpi (see https://github.com/elektro-wolle/imap-pdf-ocr/blob/3994a9809b1194eddcf60a15329ee850da7f51dd/docker/home/java/runocr.sh#L17)
I'll add an environment variable to allow a change during deployment.

**Comment by N1co93** [comment]
Thank you for the explanation and working on a solution.

**Comment by elektro-wolle** [comment]
I've release a version 2.0.0 with an additional environment variable `PDF_QUALITY` (defaults now to `/ebook` and not `/screen`, downscaling can be disabled by setting this to `none`). 

Due to the new project-layout, the location of the config-file has changed. It must now mounted to `/app/resources/config.properties`.

Sample `docker-compose.yml`:
```
version: '2'
services:
  imap-pdf-ocr:
    image: wjung/imap-pdf-ocr:2.0.0
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /services/compose/imap-ocr/config.properties:/app/resources/config.properties
```
